import { Task, Tag, Person } from './types';

export const mockTags: Tag[] = [
  { id: '1', name: 'Work', color: '#FF5733' },
  { id: '2', name: 'Personal', color: '#33FF57' },
  { id: '3', name: 'Urgent', color: '#3357FF' },
  { id: '4', name: 'Meeting', color: '#F033FF' },
  { id: '5', name: 'Shopping', color: '#FF33A8' },
];

export const mockPeople: Person[] = [
  { id: '1', name: 'John Doe' },
  { id: '2', name: 'Jane Smith' },
  { id: '3', name: 'Bob Johnson' },
  { id: '4', name: 'Alice Williams' },
  { id: '5', name: 'Charlie Brown' },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Complete project proposal',
    description: 'Finish the project proposal for the client meeting',
    date: new Date(2023, 2, 15).toISOString(),
    time: new Date(2023, 2, 15, 14, 0).toISOString(),
    completed: false,
    tags: [mockTags[0], mockTags[3]],
    invitees: [mockPeople[0], mockPeople[1]],
    priority: 'high',
    createdAt: new Date(2023, 2, 10).toISOString(),
    updatedAt: new Date(2023, 2, 10).toISOString(),
  },
  {
    id: '2',
    title: 'Buy groceries',
    description: 'Get milk, eggs, bread, and vegetables',
    date: new Date(2023, 2, 16).toISOString(),
    time: new Date(2023, 2, 16, 10, 0).toISOString(),
    completed: true,
    tags: [mockTags[1], mockTags[4]],
    invitees: [],
    priority: 'medium',
    createdAt: new Date(2023, 2, 12).toISOString(),
    updatedAt: new Date(2023, 2, 14).toISOString(),
  },
  {
    id: '3',
    title: 'Team meeting',
    description: 'Weekly team sync-up',
    date: new Date(2023, 2, 17).toISOString(),
    time: new Date(2023, 2, 17, 9, 0).toISOString(),
    completed: false,
    tags: [mockTags[0], mockTags[3]],
    invitees: [mockPeople[0], mockPeople[1], mockPeople[2], mockPeople[3]],
    priority: 'medium',
    createdAt: new Date(2023, 2, 13).toISOString(),
    updatedAt: new Date(2023, 2, 13).toISOString(),
  },
  {
    id: '4',
    title: 'Doctor appointment',
    description: 'Annual check-up',
    date: new Date(2023, 2, 18).toISOString(),
    time: new Date(2023, 2, 18, 11, 30).toISOString(),
    completed: false,
    tags: [mockTags[1], mockTags[2]],
    invitees: [],
    priority: 'high',
    createdAt: new Date(2023, 2, 5).toISOString(),
    updatedAt: new Date(2023, 2, 5).toISOString(),
  },
  {
    id: '5',
    title: 'Gym session',
    description: 'Cardio and strength training',
    date: new Date(2023, 2, 15).toISOString(),
    time: new Date(2023, 2, 15, 18, 0).toISOString(),
    completed: false,
    tags: [mockTags[1]],
    invitees: [mockPeople[4]],
    priority: 'low',
    createdAt: new Date(2023, 2, 14).toISOString(),
    updatedAt: new Date(2023, 2, 14).toISOString(),
  },
]; 